### ISSUE TITLE
No Config Menu

### ISSUE THREAD

**Issue by TheGooseman27** [Mrbysco/Padoru#1]
![Capture](https://user-images.githubusercontent.com/58607715/71289570-728b5d00-233b-11ea-8f48-8cc93104fb12.PNG)

The config menu simply doesn't exist. Could you fix that so I can set the spawn rate to maximum and fill the world with Padoru?

**Comment by Mrbysco** [comment]
That config button hasn't worked since 1.13

**Comment by TheGooseman27** [comment]
> 
> 
> That config button hasn't worked since 1.13

Alright, so how do I config?

**Comment by Mrbysco** [comment]
In your world folder there should be a folder called "serverconfigs" in there you'll find the config for Padoru
