### ISSUE TITLE
License or somecrap gnu/stallman is mad

### ISSUE THREAD

**Issue by nonetrix** [Mrbysco/Padoru#2]
Arch Linux btw java 8

Failure message: Missing License Information in file Mod File: /home/nonetrix/.local/share/multimc/instances/1.16.4/.minecraft/mods/Padoru-1.16.1-1.0.jar 

I got the mod form:
https://www.curseforge.com/minecraft/mc-mods/padoru

**Comment by nonetrix** [comment]
This is the only reason I have not ended it all please kami sama

**Comment by Mrbysco** [comment]
You should install the 1.16.3 version. You installed the 1.16.1 version
